services:
  onfridge_firmware:
    container_name: onfridge_firmware_container
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - "/dev/ttyS2:/dev/ttyUSB0"  # Windows의 COM3 -> 컨테이너 내부의 /dev/ttyUSB0
    volumes:
      - /sys:/sys  # /sys 디렉토리 마운트
    environment:
      - IDF_PATH=/esp-idf
    stdin_open: true
    tty: true
    privileged: true
    command: /app/scripts/set_new_id.sh